# site settings
title: Solid State
subtitle: by HTML5 UP
email: your@email.address
description: ANOTHER FREE + FULLY RESPONSIVE SITE TEMPLATE BY <a href="https://html5up.net/">HTML5 UP</a>
baseurl: "/solid-state-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Marburg
zip_code: 35032
country: Germany


# social settings
500px_url:
github_url:
gitlab_url: 
linkedin_url: 


# build settings
markdown: kramdown

menus:
  - Home: "/index.html"
  - Generic: "/generic.html"
  - Elements: "/elements.html"
  - Log in: "#"
  - Sign up: "#"

sass:
  style: compressed
